### ISSUE TITLE
Error message after installing

### ISSUE THREAD

**Issue by mariantanase** [akeeba/skeletonkey#1]
Hi,
-> I've installed the most recent version of Skeletonkey 1.0.1.
-> Publish the plugin
-> On Users > Manage it shows an error:
![skeletop-err](https://user-images.githubusercontent.com/3976174/174632814-1c8e8161-29f6-430e-bc3b-e0c6c1598bcb.png)

**System Information**:
Joomla 4.1.4
PHP 7.4.26

**Comment by nikosdion** [comment]
You need to publish the “Authentication - Skeleton Key” plugin as well.

**Comment by mariantanase** [comment]
Hi,
It seems that there's no "Authentication - Skeleton Key" plugin.
As you see on the screenshot, the package plg_system_skeletonkey.zip contain only "System - Skeleton Key", and this one is enabled.

![skeleton-err2](https://user-images.githubusercontent.com/3976174/174732184-a754cc6e-2501-4697-8d73-e1f7156b11ed.png)

**Comment by micker** [comment]
hello i have same error and i didn't find button to login as (maybe my fault)

**Comment by nikosdion** [comment]
Try installing https://github.com/akeeba/skeletonkey/releases/tag/1.0.3

The release script had previously uploaded the wrong file.

**Comment by mariantanase** [comment]
Thanks @nikosdion ,
This one is correct !
