### ISSUE TITLE
Feature Request: use action log for login-actions

### ISSUE THREAD

**Issue by webgras** [akeeba/skeletonkey#11]
It would be great, if the plugin would create an action log entry if someone logged in as another user. Right now, it shows that the user itself logged in, which is actually not the case.

This would make it more tracable. 
Thanks for considering!

**Comment by david-unwin** [comment]
Just a thought? As this is a Joomla Super User only function and unless you have more than one super user, you will know who is logging in as someone other than the user. Or, are you suggesting this to trace the number of times Skeleton Key is used?
David

**Comment by david-unwin** [comment]
Just a thought? As this is a Joomla Super User only function and unless you have more than one super user, you will know who is logging in as someone other than the user. Or, are you suggesting this to trace the number of times  Skeleton Key is used?
David

**Comment by webgras** [comment]
We have another usergroup with 4 users who are allowed to check frontend-login for other users.
It would also help to see, that skeleton was used.
The backend user that logged in is not so important, but would be useful to.

**Comment by webgras** [comment]
It actually is not a Super User only function. You can set the permissions in the plugin so that other usergroups are allowed to

**Comment by david-unwin** [comment]
Ok, I understand now, you give user groups other than Super User groups access to Joomla back end and access to User Management.

**Comment by nikosdion** [comment]
It sounds like a reasonable request. It will mean a third plugin, though.

**Comment by nikosdion** [comment]
The plugin is now implemented. I will eventually make a new release.
