### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by sanus70** [akeeba/skeletonkey#12]
String PLG_SYSTEM_SKELETONKEY_LBL_NOAUTHPLUGIN is missing (not defined)

**Comment by nikosdion** [comment]
It [does exist](https://github.com/akeeba/skeletonkey/blob/27b47aa67ce71936d2388c980391745d655dc2e6/plugins/system/skeletonkey/language/en-GB/plg_system_skeletonkey.ini#L16).

**Comment by sanus70** [comment]
Ok, if i change the 
plugins\system\skeletonkey\src\Extension\Skeletonkey.php
  $autoloadLanguage = true;
it works

**Comment by nikosdion** [comment]
I added a workaround so that we don't unnecessarily load the plugin language when it's not necessary (e.g. frontend, outside the Users page, etc).
