### ISSUE TITLE
How to install the latest version?

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/skeletonkey#13]
Hi Nicholas! I wanted to try out the Skeleton Key extension. I think this can be very useful for us, But I can not find the installation file of version 1.1.0.

We are on Joomla ‎5.2.2.

Kind regards, Jip.

**Comment by nikosdion** [comment]
The package file is now on https://github.com/akeeba/skeletonkey/releases/tag/1.1.0

**Comment by jjnxpct** [comment]
Thanks Nicholas!
