### ISSUE TITLE
Minor layout detail -> Space after button icon

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/skeletonkey#15]
Would it be possible to add a little space between the login button icon and the button text?
Maybe using a text space or adding a bit of styling (margin-right) to the button? 

We could override the button text by adding a space:
PLG_SYSTEM_SKELETONKEY_BTN_LABEL=" Login"
But this means we need to add the language string to the overrides on all sites we use it on. Fixing this is the code would be better I think.

**Comment by nikosdion** [comment]
It used to be the case that Joomla was adding that padding automatically back in the early 4.x versions. I see that at least in 5.1 it does not, so I have now added the `pe-1` class to do it.

**Comment by jjnxpct** [comment]
Excellent!
