### ISSUE TITLE
'Login as' backend user?

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/skeletonkey#17]
I sometimes need to login as a different user on the backend, for example to check if the user's rights are correct. To do this I open an incognito tab and then go to the admin URL and login as that user,  or use a test user with the same rights.

Would it also be possible to 'Skeleton Key' with this feature? This would probably have its own challenges I suppose. Mainly because you can't be logged in to the backend with two accounts at the same time...

I would like to hear your thoughts on this.  But no hurries., holidays are coming.

**Comment by nikosdion** [comment]
Nope, this is not dependent on an extension. Joomla uses a session. The session ID is stored in a cookie whose name is determined by your site's secret. This is hardcoded, and the session is initialized before any plugin can run, meaning that the only way to somehow select which session to use would require hacking core which is a big no-no. As a result, you cannot have two or more sets of sessions. Ultimately, it's up to the way your browser handles cookies a.k.a. its “cookie jar”.

There are two ways I know of which allow you to use a different cookie jar on the same browser.

The obvious approach is what you said: opening a private browsing session. This not only uses a separate cookie jar, but one which is ephemeral at that (it gets emptied when you close the browser window or tab, depending on the browser and its settings).

The other approach is to use different profiles. As far as major browsers go, this is universally supported, e.g. in [Firefox](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US), [Chrome](https://support.google.com/chrome/answer/2364824?hl=en&co=GENIE.Platform=Desktop) (and other Chromium-based browsers), and [Safari](https://support.apple.com/en-us/105100). In practice, this method sucks on all browsers _except Safari_ as you can only have one profile active at any given time. Safari is actually pretty darned good, allowing you to have multiple profiles active (in different windows, of course) at the same time.

The corollary of each browser having its own cookie jar per browser profile gives us, of course, a third option: having multiple browsers, or multiple devices. This is something we do use ourselves –along with Safari profiles– when we need to have access to the backend as User A and on the frontend as User B. If you are on Windows you can install a portable version of your browser of choice using the installers in PortableApps.com, e.g. [Google Chrome Portable](https://portableapps.com/apps/internet/google_chrome_portable). You can actually have as many copies of the same portable browser as you want, and load them all at the same time; each one will have its own cookie jar.

**Comment by jjnxpct** [comment]
Thanks for explaining this Nicholas. I kinda already thought this would be impossible to do with a plugin. For now I'll just stick with logging in in a incognito browser with a test user in the same group as the user I want to check the rights for, It works. I am just always looking for ways to speed up my workflow.  This plugin helps with that. So thanks for that! Happy Holidays!
