### ISSUE TITLE
JAuthentication: :authenticate: Failed to load plugin: plgauthenticationskeletonkey

### ISSUE THREAD

**Issue by stratacorps** [akeeba/skeletonkey#4]
Version 1.0.4. Also downloaded the latest /authentication and /system files from github. J4.2.7, PHP 8.1.14

There are no options in the User listing (default J4 Atum administrator template) for logging in as user, and in the front-end when logging in with a Super User password and a Registered user's username, we get:

JAuthentication: :authenticate: Failed to load plugin: plgauthenticationskeletonkey

WIth debug and error reporting on, the only thing that appears to be related to the authentication process that shows up when the plugins are enabled is this:

PHP message: PHP Warning:  Undefined property: Joomla\\CMS\\Extension\\DummyPlugin::$name in /var/www/libraries/src/Authentication/Authentication.php on line 170

With the plugin/s disabled, and normal Joomla authentication that doesn't show up, so posted it here in case it was related to the skeletonkey plugins.

**Comment by nikosdion** [comment]
It sounds like you have messed up the installation. Copying files from the repository will not work. There is a build step to create the packages.

Disable the two plugins and uninstall the SkeletonKey package. If it leaves behind either or both of the two plugins, remove them as well.

Then install the SkeletonKey 1.0.4 package twice in a row, without uninstalling it before or in between.

Make sure BOTH plugins are enabled.

If you do not see the buttons in the backend Users management page (when logged in as a Super User; this is a prerequisite) you have a JavaScript problem in the backend of your site.

**Comment by stratacorps** [comment]
The repeat installation fixed it. (I used the 1.0.4 install package first, I only copied the updated files from git after it didn't work). I installed a new J4 site, no plugins, etc. and had to do what you said--install, then install again immediately--otherwise the Login button doesn't show up.

Thank you!

**Comment by nikosdion** [comment]
You're welcome!

This is a problem in Joomla I have first seen in Joomla 1.5.5 in 2008. Sometimes on update or installation some files are not copied. It happens **extremely** rarely, making it one of those things which we know exist, annoy the bleeping bleepety bleep out of us, but can't reproduce in order to debug.

If anyone finds a way to reproduce reliably, please contact me. I've been chasing this white whale of a bug for 15 years.
