### ISSUE TITLE
The checksum verification failed. Please make sure you are using the correct update server!

### ISSUE THREAD

**Issue by mariantanase** [akeeba/skeletonkey#6]
Hi,
When I use automatic update from 1.0.4 to 1.0.5, I receive this error:
"_The checksum verification failed. Please make sure you are using the correct update server!_"

I think the issue is related to another old one. (#2 )
Can you check please ?

Thanks

**Comment by nikosdion** [comment]
Yep, that was the same issue. I have fixed it now.
