### ISSUE TITLE
Login does not divert to normal login setting

### ISSUE THREAD

**Issue by Seahawk59** [akeeba/skeletonkey#7]
When you use the plugin, and Joomla is set to divert to View Profile after login, this does not happen when you login with the plugin. It logs in but stays on the front page. 

Any reason why this would happen?

**Comment by nikosdion** [comment]
This plugin works a lot like cookie authentication (the Remember Me feature). The difference is that we convince Joomla to "remember" that a _different user_ is logged in. Therefore, Joomla does not go through the settings in the login module or the Users component; it just says "ah, this user is already logged in, let me adjust my user session".
