### ISSUE TITLE
Joomla 5 Is Skeleton Key compatible?

### ISSUE THREAD

**Issue by david-unwin** [akeeba/skeletonkey#8]
Just checking if Skeleton Key works under Joomla 5 as I get the message when checking for update issues with Joomla 5 (see screenshot)
![skeleton key Package](https://github.com/user-attachments/assets/216dfcfb-81d4-4029-8e28-ad84e1b4ebb5)

Kind regards
David

**Comment by nikosdion** [comment]
It is compatible, but currently does not appear at all on Joomla! 5.2's User Manager. It's on my to-do… and I should probably add a GitHub issue for it. Thanks for the (unintended) reminder 😅

**Comment by david-unwin** [comment]
Thanks for clarification.
David

**Comment by david-unwin** [comment]
Confirm that no warning message on Pre Update check for Joomla 5.1.4

**Comment by nikosdion** [comment]
Yep, I fixed the update file to indicate compatibility with Joomla! 5.x versions beyond 5.0.

I just released a new version which fixes a bug which only takes place with some database drivers. You may want to install it if you see the buttons disappear after updating to Joomla! 5.1.

**Comment by david-unwin** [comment]
Thanks!
